# Generated by Django 3.2.12 on 2022-11-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_cost', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='subsc_directory',
            name='table_prices',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
