# Generated by Django 3.2.12 on 2022-11-20 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_auto_20221119_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boot_directory',
            options={'verbose_name_plural': 'Boots'},
        ),
        migrations.AlterModelOptions(
            name='payment_history',
            options={'verbose_name_plural': 'Payment history'},
        ),
        migrations.AlterModelOptions(
            name='resort_contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='resort_directory',
            options={'verbose_name_plural': 'Resorts'},
        ),
        migrations.AlterModelOptions(
            name='ski_directory',
            options={'verbose_name_plural': 'Ski'},
        ),
        migrations.AlterModelOptions(
            name='subsc_directory',
            options={'verbose_name_plural': 'Subscription'},
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=120)),
                ('temp', models.IntegerField()),
                ('resort_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_app.resort_directory')),
            ],
        ),
    ]
