# Generated by Django 3.2.12 on 2022-11-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0004_auto_20221120_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp',
            field=models.IntegerField(),
        ),
    ]
