# Generated by Django 3.2.12 on 2022-11-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_auto_20221120_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
