# Generated by Django 3.2.12 on 2022-11-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0012_alter_weather_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='resort_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='rent_app.resort_directory'),
        ),
    ]
